-- nhs_ae_batch_01_07_2020.sqlx
config {
  type: "table",
  schema: "DE_2025_final_DW",
  name: "nhs_ae_batch_01_07_2020",
  description: "Internal BigQuery table populated from external CSV data.",
  dependencies: ["nhs_ae_gcs_upload_01_07_2020"]
}

SELECT
  *
  -- Add columns missing in the earliest extracts
  ,NULL AS A_E_attendances_Booked_Appointments_Type_1
  ,NULL AS A_E_attendances_Booked_Appointments_Type_2
  ,NULL AS A_E_attendances_Booked_Appointments_Other_Department
  ,NULL AS Attendances_over_4hrs_Booked_Appointments_Type_1
  ,NULL AS Attendances_over_4hrs_Booked_Appointments_Type_2
  ,NULL AS Attendances_over_4hrs_Booked_Appointments_Other_Department

FROM
  ${ref("nhs_ae_gcs_upload_01_07_2020")}
WHERE Period IS NOT NULL