-- nhs_ae_gcs_upload_08_2020_2025.sqlx
config {
  type: "table",
  schema: "DE_2025_final_DW",
  name: "nhs_ae_batch_08_2020_2025",
  description: "Internal BigQuery table populated from external CSV data.",
  dependencies: ["nhs_ae_gcs_upload_08_2020_2025"],
  assertions: {
    nonNull: ["Period", "Parent_Org", "Org_Name"]
  }
}

SELECT
  *
FROM
  ${ref("nhs_ae_gcs_upload_08_2020_2025")}
WHERE Period IS NOT NULL